InformacoesMarvel/Models/ComicsVM.cs
using System.Collections.Generic;

namespace InformacoesMarvel.Models
{
    public class ComicsVM
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public List<string> Criadores { get; set; }
        public List<PersonagemVM> Personagens { get; set; }
        public string ImagemPath { get; set; }
        public int QuantidadeDePaginas { get; set; }
        public List<string> Descricao { get; set; }
        public string ResourceURI { get; set; }
    }
}

InformacoesMarvel/Models/ErrorViewModel.cs
using System;

namespace InformacoesMarvel.Models
{
    public class ErrorViewModel
    {
        public int ErroCode { get; set; }
        public string Titulo { get; set; }
        public string Mensagem { get; set; }
    }
}

InformacoesMarvel/Models/PersonagemVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InformacoesMarvel.Models
{
    public class PersonagemVM
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string ImagemPath { get; set; }
        public string Descricao { get; set; }
        public List<ComicsVM> Comics { get; set; }

    }
}

InformacoesMarvel/Controllers/HomeController.cs
using InformacoesMarvel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace InformacoesMarvel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [Route("erro/{id:length(3,3)}")]
        public IActionResult Error(int id)
        {
            var modelErro = new ErrorViewModel();

            if (id == 500)
            {
                modelErro.Mensagem = "Ocorreu um erro! Tente novamente mais tarde ou contate nosso suporte.";
                modelErro.Titulo = "Ocorreu um erro!";
                modelErro.ErroCode = id;
            }
            else if (id == 401)
            {
                modelErro.Mensagem =
                    "Você não está autenticado! <br />Em caso de dúvidas entre em contato com nosso suporte";
                modelErro.Titulo = "Ops! Página não encontrada.";
                modelErro.ErroCode = id;
            }
            else if (id == 404)
            {
                modelErro.Mensagem =
                    "A página que está procurando não existe! <br />Em caso de dúvidas entre em contato com nosso suporte";
                modelErro.Titulo = "Ops! Página não encontrada.";
                modelErro.ErroCode = id;
            }
            else if (id == 403)
            {
                modelErro.Mensagem = "Você não tem permissão para fazer isto.";
                modelErro.Titulo = "Acesso Negado";
                modelErro.ErroCode = id;
            }
            else
            {
                return StatusCode(404);
            }

            return View("Error", modelErro);
        }
    }
}

InformacoesMarvel/Controllers/MainController.cs
using InformacoesMarvel.Models;
using InformacoesMarvel.Servico.ServicoMarvelModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InformacoesMarvel.Controllers
{
    public class MainController : Controller
    {
        //Erros de Response exibidos através de ModelState
        protected bool VerificaErrosNoResponse(ErroResponse erro)
        {
            if (erro != null)
            {
                ModelState.AddModelError(string.Empty, erro.Code);
                return true;
            }
            return false;
        }

        
    }
}

InformacoesMarvel/Controllers/MarvelComicsController.cs
using InformacoesMarvel.Servico;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InformacoesMarvel.Controllers
{
    public class MarvelComicsController : MainController
    {
        private readonly IMarvelService _servicoMarvel;

        public MarvelComicsController(IMarvelService servicoMarvel)
        {
            _servicoMarvel = servicoMarvel;
        }
        
        public async Task<IActionResult> Index(int limit = 70, int offset = 1)
        {
            var result = await _servicoMarvel.Comics(limit, offset);
            VerificaErrosNoResponse(result.ErrosReponse);
            return View(result.Values);
        }

        public async Task<IActionResult> Comic(int id)
        {
            var result = await _servicoMarvel.Comic(id);
            VerificaErrosNoResponse(result.ErrosReponse);
            return View(result.Value);
        }

        public async Task<IActionResult> IndexPersonagens()
        {
            var result = await _servicoMarvel.TotalPersonagens();
            ViewData["TotalPersonagens"] = result;
            return View();
        }

        public async Task<IActionResult> Personagens(int limit=70, int offset=1)
        {
            var result = await _servicoMarvel.Personagens(limit, offset);
            VerificaErrosNoResponse(result.ErrosReponse);
            return PartialView("_partialGridPersonagens", result.Values);
        }

        public async Task<IActionResult> Personagem(int id)
        {
            var result = await _servicoMarvel.Personagem(id);
            VerificaErrosNoResponse(result.ErrosReponse);
            return View(result.Value);
        }
    }
}

InformacoesMarvel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InformacoesMarvel/Views/MarvelComics/Comic.cshtml
@model InformacoesMarvel.Models.ComicsVM


<vc:Summary></vc:Summary>

<div class="mb-5">
    <div class="card border-secondary-2">
        <img src="@Html.DisplayFor(p => p.ImagemPath)" class="card-img-top" alt="...">
        <div class="card-body">
            <h1 class="card-title text-wrap">@Html.DisplayFor(p => p.Titulo)</h1>
            <p class="card-text">@Html.DisplayFor(p => p.Descricao)</p>
        </div>
    </div>
</div>


<h2 class="mt-5">
    Personagens
</h2>

<div class="row mt-5">

    @if (Model.Personagens != null && Model.Personagens.Any())
    {
        @foreach (var item in Model.Personagens)
        {
            <div class="col-sm-6 col-lg-3 mb-5">
                <div class="card border-secondary-2">
                    <img src="@Html.DisplayFor(modelItem => item.ImagemPath)" class="img-revista-miniatura" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-wrap">@Html.DisplayFor(model => item.Nome)</h5>
                        <a asp-action="Personagem" asp-route-id="@item.Id" class="btn btn-outline-secondary">More</a>
                    </div>
                </div>
            </div>
        }

    }
    else
    {
        <h5 class="mt-5">Não foram econtrados registros!</h5>
    }
</div>

InformacoesMarvel/Views/MarvelComics/Index.cshtml
@model IEnumerable<InformacoesMarvel.Models.ComicsVM>

@{
    ViewData["Title"] = "Lista de Títulos da MARVEL";
}

<h1>Index</h1>


@if (Model != null && Model.Any())
{
    <!-- Future navigation panel -->
    <div class="holder"></div>

    @*<div class="row mt-5">*@
    <ul id="itemContainer" class="row">
        @foreach (var item in Model)
        {
            <li>

                <div class="col-sm-6 col-lg-3 mb-5">
                    <div class="card border-secondary-2">
                        <img src="@Html.DisplayFor(modelItem => item.ImagemPath)" class="img-revista-miniatura" alt="...">
                        <div class="card-body">
                            <h5 class="card-title text-wrap">@Html.DisplayFor(model => item.Titulo)</h5>
                            <a asp-action="Comic" asp-route-id="@item.Id" class="btn btn-outline-secondary">More</a>
                        </div>
                    </div>
                </div>

            </li>
        }
    </ul>
    @*</div>*@

}
else
{
    <h5 class="mt-5">Não foram econtrados registros para essa soclicitação!</h5>
}

InformacoesMarvel/Views/MarvelComics/IndexPersonagens.cshtml
@{
    ViewData["Title"] = "Lista de Títulos da MARVEL";
    var total = Convert.ToInt32(ViewData["TotalPersonagens"].ToString());
    var paginas = total / 72 + 1;
}

<h1>Personagens do Mundo MARVEL</h1>


<div class="container">
    <div class="row">
        <p>Listados 72 de @total.</p>
    </div>    
</div>


<div id="div-persongens">

</div>


<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item previous" data-pag="1">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
        @for (int i = 1; i < (paginas + 1); i++)
        {
            <li class="page-item">
                <a class="page-link" href="#">@i</a>
            </li>
        }
        <li class="page-item next">
            <a class="page-link" href="#">Next</a>
        </li>
    </ul>
</nav>


@section Scripts{

    <script>

        var paginaAtual = 1;
        var offSet = 1;

        $(document).ready(function () {
            CarregarPersonagens(offSet);
            PreviousEnabledDisabled();
        });

        $(".page-item").click(function () {
            var numeroDaPagina = $(this).find("a").text();
            $(".page-item").removeClass("active");
            $(this).addClass("active");

            paginaAtual = numeroDaPagina;
            offSet = (numeroDaPagina * 70 - 70) + 1;

            PreviousEnabledDisabled();
            NextEnabledDisabled();

            CarregarPersonagens(offSet);
        })

        function CarregarPersonagens(offSet) {
            $.ajax({
                type: 'GET',
                url: "/MarvelComics/Personagens",
                data: {
                    "offset": offSet
                },
                dataType: "html",
                success: function (data) {

                    $("#div-persongens").html("");
                    $("#div-persongens").html(data);

                },
                error: function (err) {
                    //console.log(err)
                    //alert(err.responseText);
                    $("#div-persongens").html("");
                    $("#div-persongens").html(err.responseText);
                }
            })
        }

        function PreviousEnabledDisabled() {
            if (paginaAtual == 1) {
                $(".previous").addClass("disabled");
            } else {
                $(".previous").removeClass("disabled");
            }
        }

        function NextEnabledDisabled() {
            if (paginaAtual == 23) {
                $(".next").addClass("disabled");
            } else {
                $(".next").removeClass("disabled");
            }
        }

    </script>

}

InformacoesMarvel/Views/MarvelComics/Personagem.cshtml
@model InformacoesMarvel.Models.PersonagemVM


    <vc:Summary></vc:Summary>
    
    <div class="mb-5">
        <div class="card border-secondary-2">
            <img src="@Html.DisplayFor(p => p.ImagemPath)" class="card-img-top" alt="...">
            <div class="card-body">
                <h1 class="card-title text-wrap">@Html.DisplayFor(p => p.Nome)</h1>
                <p class="card-text">@Html.DisplayFor(p => p.Descricao)</p>
            </div>
        </div>
    </div>

    
    <h2 class="mt-5">
        Revistas em que participa
    </h2>

    <div class="row mt-5">
    
        @if (Model.Comics != null && Model.Comics.Any())
        {
            @foreach (var item in Model.Comics)
            {
                <div class="col-sm-6 col-lg-3 mb-5">
                    <div class="card border-secondary-2">
                        <img src="@Html.DisplayFor(modelItem => item.ImagemPath)" class="img-revista-miniatura" alt="...">
                        <div class="card-body">
                            <h5 class="card-title text-wrap">@Html.DisplayFor(model => item.Titulo)</h5>                        
                            <a asp-action="Comic" asp-route-id="@item.Id" class="btn btn-outline-secondary">More</a>
                        </div>
                    </div>
                </div>
            }

        }
        else
        {
            <h5 class="mt-5">Não foram econtrados registros para essa soclicitação!</h5>
        }
    </div>

InformacoesMarvel/Views/MarvelComics/_partialGridPersonagens.cshtml
@model IEnumerable<InformacoesMarvel.Models.PersonagemVM>

<div class="row">
    <vc:Summary></vc:Summary>
    @if (Model != null && Model.Any())
    {
        @foreach (var item in Model)
        {
            <div class="col-sm-6 col-lg-3 mb-5">
                <div class="card border-secondary-2">
                    <img src="@Html.DisplayFor(modelItem => item.ImagemPath)" class="img-personagem-miniatura" alt="...">
                    <div class="card-body">
                        <h5 class="card-title text-wrap">@Html.DisplayFor(model => item.Nome)</h5>
                        @*<p class="card-text">@Html.DisplayFor(model => item.Descricao)</p>*@
                        <a asp-action="Personagem" asp-route-id="@item.Id" class="btn btn-outline-secondary">More</a>
                    </div>
                </div>
            </div>
        }

    }
    else
    {
        <h5 class="mt-5">Não foram econtrados registros para essa soclicitação!</h5>
    }
</div>

InformacoesMarvel/Views/Shared/Components/Summary/Default.cshtml
@if (ViewData.ModelState.ErrorCount > 0)
{
    <div style="padding-top: 15px;"></div>
    
    <div class="alert alert-danger col-sm-12">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <h3 style="padding-top: 20px;">Algo deu muito Errado! :(</h3>
        <div style="padding-top: 20px;" asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
        
}

InformacoesMarvel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InformacoesMarvel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/Jpages/jPages.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InformacoesMarvel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MarvelComics" asp-action="Index">Comics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MarvelComics" asp-action="IndexPersonagens">Personagens</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - InformacoesMarvel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="~/lib/Jpages/jPages.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>